stages:
- name: Test
  steps:
  - runScriptConfig:
      image: node:11
      shellScript: |-
        npm install
        npm run build
        npm run start &
        npm run test
timeout: 60
notification: {}
