stages:
- name: Build Test
  steps:
  - runScriptConfig:
      image: node:11
      shellScript: |-
        npm install
        npm run build
- name: App Test
  steps:
  - runScriptConfig:
      image: node:11
      shellScript: npm run test
timeout: 60
notification: {}
