stages:
- name: Build Test
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: bjornadalno/rancher-pipeline-nodejs-example:${CICD_GIT_COMMIT}
      registry: index.docker.io
- name: App Test
  steps:
  - runScriptConfig:
      image: node:11
      shellScript: npm run test
  - runScriptConfig:
      image: node:10
      shellScript: npm run test
  - runScriptConfig:
      image: node:6
      shellScript: npm run test
- name: Build and Push
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: bjornadalno/${CICD_GIT_REPO_NAME}:latest,stable,1,1.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: index.docker.io
timeout: 60
notification: {}
