stages:
- name: Build Test
  steps:
  - runScriptConfig:
      image: node:11
      shellScript: |-
        npm install
        npm run build
- name: App Test
  steps:
  - runScriptConfig:
      image: node:11
      shellScript: npm run test
  - runScriptConfig:
      image: node:10
      shellScript: npm run test
  - runScriptConfig:
      image: node:6
      shellScript: npm run test
- name: Build and Push
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: bjornadalno/${CICD_GIT_REPO_NAME}:1,1.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: index.docker.io
timeout: 60
notification: {}
