stages:
- name: Test
  steps:
  - runScriptConfig:
      image: node:11
      shellScript: |-
        npm install
        npm run build
        npm run test
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ${CICD_GIT_REPO_NAME}:${CICD_GIT_COMMIT}
      registry: 127.0.0.1:34725
- name: Push
  steps:
  - runScriptConfig:
      image: docker:dind
      shellScript: |-
        echo ${CICD_GIT_TAG}
        echo ${CICD_EVENT}
        docker image ls
timeout: 60
notification: {}
