stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ${CICD_GIT_REPO_NAME}:${CICD_GIT_COMMIT}
      registry: index.docker.io
- name: Test
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: exit 1
timeout: 60
notification: {}
