stages:
- name: Test
  steps:
  - runScriptConfig:
      image: node:11
      shellScript: |-
        npm install
        npm run build
        npm run test
- name: Build and Push
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: bjornadalno/${CICD_GIT_REPO_NAME}:latest
      pushRemote: true
      registry: index.docker.io
timeout: 60
notification: {}
