kind: Service
apiVersion: v1
metadata:
  name: pipeline-service
  namespace: pipelinetest
spec:
  selector:
    app: pipelineexample
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: pipeline-nodejs-api-pod
  namespace: pipelinetest
  labels:
    app: pipelineexample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipelineexample
  template:
    metadata:
      labels:
        app: pipelineexample
    spec:
      imagePullSecrets:
      - name: dc-7kg8f
      containers:
      - name: pipeline-nodejs-api-container
        image: ${CICD_IMAGE}:stable
        ports:
        - containerPort: 80
